# Generated by Django 5.1.7 on 2025-03-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentform',
            old_name='zip',
            new_name='pincode',
        ),
        migrations.RemoveField(
            model_name='employmentform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employmentform',
            name='cover_letter',
        ),
    ]
